[package]
name = "sozu-prometheus-connector"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0.66"
clap = { version = "4.1.4", features = ["derive"] }
axum = {version = "0.6.18", features = ["tokio"] }
sozu-command-lib = "^0.14.3"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tracing = "^0.1.37"
tracing-subscriber = "^0.3.16"
