# Socket address on which to listen
listening-address = "0.0.0.0:3000"

# aggregate backend metrics by cluster id
aggregate-backend-metrics = true

[sozu]
# Path to Sōzu's configuration file
configuration = "path/to/sozu/config.toml"

[sentry]
# The Data Source Name of our API
dsn = "https://..."
# See https://docs.rs/sentry/0.31.3/sentry/struct.ClientOptions.html#structfield.environment
environment = "production"
