---
name: CI
on: [ push, pull_request ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental: [false]
        rust:
          - stable
          - beta
          - 1.88.0
        include:
          - rust: nightly
            experimental: true
    steps:
      - name: install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust (${{ matrix.rust }})
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy, rustfmt
      - name: Build
        run: cargo build --all-features
      - name: Test
        run: cargo test --all-features --verbose

  lint:
    name: Lint (fmt + clippy)
    runs-on: ubuntu-latest
    steps:
      - name: install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.88.0"
          components: clippy, rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-features -- -D warnings
...
